### ISSUE TITLE
changing default/first admin email using email already in use

### ISSUE THREAD

**Issue by peareye** [peareye/mypie#26]
When I tried to change the email address from peareye@yahoo.com to peri.moritz@gmail.com I got an error (see below). It is obvious that it was an email address that was already in the system, just might die more gracefully.

Slim Application Error
The application could not run because of the following error:

Details
Type: PDOException
Code: 23000
Message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'peri.moritz@gmail.com' for key 'email_uq'
File: /var/www/mypie/app/Models/DataMapperAbstract.php
Line: 497
Trace

**Comment by wolfmoritz** [comment]
Removed constraint f447019
