### ISSUE TITLE
Calendar rows

### ISSUE THREAD

**Issue by peareye** [peareye/mypie#37]
The calendar for Sept/Oct/Nov is currently displayed.  

The month of September presents an entire row that is only October.
The month of October presents an entire row that is only September.
The month of November is only November with a few days of October & December to create the entire calendar grid.

Is this a bug or a feature?

<img width="515" alt="screen shot 2018-09-20 at 1 28 13 pm" src="https://user-images.githubusercontent.com/11490640/45818529-e7578d80-bcd9-11e8-847e-ffc73eae28dc.png">
<img width="511" alt="screen shot 2018-09-20 at 1 28 24 pm" src="https://user-images.githubusercontent.com/11490640/45818530-e7578d80-bcd9-11e8-8044-0eefbf6b949a.png">
<img width="515" alt="screen shot 2018-09-20 at 1 28 41 pm" src="https://user-images.githubusercontent.com/11490640/45818531-e7f02400-bcd9-11e8-9af5-d6615ae64f21.png">

**Comment by wolfmoritz** [comment]
Feature removed in 3cd37b9
